version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rocketseat-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - primeira-rede


  docker-api:
    build:
      context: .
    container_name: docker-api
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - primeira-rede


networks:
  primeira-rede:
    name: primeira-rede
    external: true
    driver: bridge
